services:
  app:
    build: .
    container_name: syncord-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6060:6379"  # Optional unless you want to connect to Redis from host
    restart: unless-stopped
